feat(openbmc): Create a new OpenBMC brand and utilize a common brand
Seagate/SystemsRedfishPy pull request #8
Opened 2022-08-02 03:12 UTC by jskazinski

The main purpose of this new feature is to pave the way for OpenBMC command support. This is only a start at supporting OpenBMC commands and a common brand was created where commands are the same for all Redfish Services.

Release Notes:

- Created new 'common' command folder. Brand is searched first, then common.
- Added new 'show brands' command which displays all brands and a command count.
- Moved many commands from 'systems' and 'example' to 'common'
- Minor bug correction in 'create session'
- Created a new Open BMC brand (obmc) as a starting point

Signed-off-by: Joe Skazinski <joseph.skazinski@seagate.com>

2022-08-15 16:41 UTC, mjenglish approved these changes
- show_brands.py
- create_account.py
- get_accounts.py
- redfishCommand.py

Overall, this looks good and I approve. There are some smaller comments that I'll make during our meeting today.

2022-08-15 16:59 UTC, scott-howe-1 approved these changes

2022-08-15 20:06 UTC, mjenglish requested changes

2022-08-15 22:07 UTC, scott-howe-1 commented on commands/obmc/create_account.py
> +
@mjenglish, At this point, these sort of whitespace corrections are best left to a separate, general discussion about coding standards for this project.  What we enforce and what we don't.   I don't want to unnecessarily add to the size of these PR's with back-and-forth opinions about how whitespace should be handled.  We should have that discussion once, then just enforce it via the PR's.
However, I do not see a `coding_standard.md` type file for this project yet, so we may need to add that to the todo list.

2022-08-15 22:10 UTC, mjenglish commented on commands/obmc/create_account.py
> +
These are requested changes, not required changes.

2022-08-15 22:39 UTC, scott-howe-1 commented on commands/obmc/create_account.py
> +
That statement implies that I'm not allowed to have an opinion on your suggestion (which I know is **_not_** the message you intended to send).

If I think the space is fine, am I now going to have to make a comment to every one of these types of formatting comments to keep it? 
The presence of these types of formatting comments in the PR's force team members to spent time on them.  One person creating them.  Others interpreting them.  It's a waste of time and something a coding standard solves. 

One thing to keep in mind with these PR's is the difference between a `functional change` and `stylistic change`.  Your `for-loop` suggestion further down is an excellent example of a useful `functional change`.  These whitespace formatting discussions are subjective `stylistic changes` that can create unnecessary back-and-forth.

2022-08-19 00:03 UTC, jskazinski commented on commands/obmc/get_accounts.py
> +                self.UserName = link.jsonData['UserName']
Excellent simplification of code, thank you.

2022-08-19 00:08 UTC, jskazinski commented on core/redfishCommand.py
> +                handlerFile = 'commands/' + brand + '/' + words[0] + '.py'
Agreed. 'brand' should be validated when that configuration setting is updated and the command line values like word[0] should be validated here. A separate issue will be created.

2022-08-19 01:46 UTC, jskazinski commented on commands/obmc/get_accounts.py
> +        # Retrieve a link to Accounts
I would say that the purpose of this method is to store account data for display, which when using a Redfish API takes four steps. I would agree that improvements can be made to this function, and to all functions that do very similar code, but I request that this be done in a separate ticket. I did address the width being set to a magic number, and that function can be reused in other display functions.

2022-08-24 15:42 UTC, merged